/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app;

/**
 *
 * @author professional
 */
public class AboutPanel extends javax.swing.JPanel {

    /**
     * Creates new form AboutPanel
     */
    Admin adminFrame;
    
    public AboutPanel(Admin adminFrame) {
        initComponents();
        this.adminFrame = adminFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        versionInfoLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        developedLabel = new javax.swing.JLabel();
        memberLabel1 = new javax.swing.JLabel();
        memberLabel2 = new javax.swing.JLabel();
        memberLabel3 = new javax.swing.JLabel();
        memberLabel4 = new javax.swing.JLabel();

        titleLabel.setFont(new java.awt.Font("Walt Disney Script v4.1", 3, 70)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(153, 0, 255));
        titleLabel.setText("Catechizer");

        versionInfoLabel.setFont(new java.awt.Font("Old English Text MT", 1, 36)); // NOI18N
        versionInfoLabel.setForeground(new java.awt.Color(204, 153, 255));
        versionInfoLabel.setText("Version : ");

        versionLabel.setFont(new java.awt.Font("Walt Disney Script v4.1", 1, 36)); // NOI18N
        versionLabel.setForeground(new java.awt.Color(153, 0, 153));
        versionLabel.setText("1.0");

        developedLabel.setFont(new java.awt.Font("Old English Text MT", 1, 36)); // NOI18N
        developedLabel.setForeground(new java.awt.Color(204, 153, 255));
        developedLabel.setText("Developed By : ");

        memberLabel1.setFont(new java.awt.Font("Walt Disney Script v4.1", 1, 48)); // NOI18N
        memberLabel1.setForeground(new java.awt.Color(153, 0, 153));
        memberLabel1.setText("Harchandani Dolly");

        memberLabel2.setFont(new java.awt.Font("Walt Disney Script v4.1", 1, 48)); // NOI18N
        memberLabel2.setForeground(new java.awt.Color(153, 0, 153));
        memberLabel2.setText("Kundnani Vinu");

        memberLabel3.setFont(new java.awt.Font("Walt Disney Script v4.1", 1, 48)); // NOI18N
        memberLabel3.setForeground(new java.awt.Color(153, 0, 153));
        memberLabel3.setText("Duseja Sneha");

        memberLabel4.setFont(new java.awt.Font("Walt Disney Script v4.1", 1, 48)); // NOI18N
        memberLabel4.setForeground(new java.awt.Color(153, 0, 153));
        memberLabel4.setText("Dewani Bhavna");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(versionInfoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(versionLabel))
                    .addComponent(developedLabel)
                    .addComponent(memberLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versionInfoLabel)
                    .addComponent(versionLabel))
                .addGap(18, 18, 18)
                .addComponent(developedLabel)
                .addGap(18, 18, 18)
                .addComponent(memberLabel1)
                .addGap(18, 18, 18)
                .addComponent(memberLabel4)
                .addGap(18, 18, 18)
                .addComponent(memberLabel2)
                .addGap(18, 18, 18)
                .addComponent(memberLabel3)
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel developedLabel;
    private javax.swing.JLabel memberLabel1;
    private javax.swing.JLabel memberLabel2;
    private javax.swing.JLabel memberLabel3;
    private javax.swing.JLabel memberLabel4;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel versionInfoLabel;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}
