/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Jacky
 */
public class AddNewSubjectPanel extends javax.swing.JPanel {

    Admin adminFrame;
    private JPanel contentPanel;
    String subjectName;
    String standard;

    /**
     * Creates new form AddNewSubjectPanel
     */
    AddNewSubjectPanel(AddQuestionToDatabase aThis, Admin adminFrame) {
        initComponents();
        this.adminFrame = adminFrame;
        standardComboBox.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        standardLabel = new javax.swing.JLabel();
        standardComboBox = new javax.swing.JComboBox();
        newSubjectNameLabel = new javax.swing.JLabel();
        newSubjectNameTextField = new javax.swing.JTextField();
        nextButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        standardLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        standardLabel.setText("Standard");

        standardComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "IX", "X" }));
        standardComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                standardComboBoxItemStateChanged(evt);
            }
        });
        standardComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardComboBoxActionPerformed(evt);
            }
        });

        newSubjectNameLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        newSubjectNameLabel.setText("Subject Name");

        nextButton.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        nextButton.setText("NEXT");
        nextButton.setBorderPainted(false);
        nextButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nextButton.setIconTextGap(0);
        nextButton.setOpaque(false);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        cancelButton.setText("CANCEL");
        cancelButton.setBorderPainted(false);
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancelButton.setIconTextGap(0);
        cancelButton.setOpaque(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(standardLabel)
                    .addComponent(newSubjectNameLabel))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(standardComboBox, 0, 185, Short.MAX_VALUE)
                    .addComponent(newSubjectNameTextField))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextButton)
                .addGap(28, 28, 28)
                .addComponent(cancelButton)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(standardLabel)
                    .addComponent(standardComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newSubjectNameLabel)
                    .addComponent(newSubjectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton)
                    .addComponent(cancelButton))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void standardComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardComboBoxActionPerformed

        standard = standardComboBox.getSelectedItem().toString();
        int num = standard.equals("IX") ? 9 : 10;
        subjectName = newSubjectNameTextField.getText();
    }//GEN-LAST:event_standardComboBoxActionPerformed

    private void standardComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_standardComboBoxItemStateChanged
    }//GEN-LAST:event_standardComboBoxItemStateChanged

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed

        if (newSubjectNameTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(adminFrame, "Enter a name for subject!!");
        } else {
            contentPanel = new JPanel(new BorderLayout());
            adminFrame.rightPanel = new AddNewQuestionsPanel(adminFrame, subjectName, standard);

            adminFrame.jSplitPane1 = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, true, adminFrame.leftPanel, adminFrame.rightPanel);
            adminFrame.jSplitPane1.setDividerLocation(120);

            contentPanel.add(adminFrame.jSplitPane1, BorderLayout.CENTER);
            adminFrame.setContentPane(contentPanel);
            adminFrame.getRootPane().updateUI();
            SwingUtilities.updateComponentTreeUI(this);
        }
        }//GEN-LAST:event_nextButtonActionPerformed

        private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
            this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel newSubjectNameLabel;
    private javax.swing.JTextField newSubjectNameTextField;
    private javax.swing.JButton nextButton;
    private javax.swing.JComboBox standardComboBox;
    private javax.swing.JLabel standardLabel;
    // End of variables declaration//GEN-END:variables
}
