/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app;

import java.awt.BorderLayout;
import javax.swing.*;

/**
 *
 * @author Jacky
 */
public class AddQuestionToDatabase extends javax.swing.JPanel {

    Admin adminFrame;
    private JPanel contentPanel;

    /**
     * Creates new form AddQuestionToDatabase
     */
    public AddQuestionToDatabase(Admin adminFrame) {
        initComponents();
        this.adminFrame = adminFrame;
        ButtonGroup b = new ButtonGroup();
        b.add(addANewSubjectRadioButton);
        b.add(addToExistingSubjectRadioButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addToExistingSubjectRadioButton = new javax.swing.JRadioButton();
        addANewSubjectRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        addToExistingSubjectRadioButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        addToExistingSubjectRadioButton.setText("Add to existing subject");
        addToExistingSubjectRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                addToExistingSubjectRadioButtonItemStateChanged(evt);
            }
        });
        addToExistingSubjectRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToExistingSubjectRadioButtonActionPerformed(evt);
            }
        });

        addANewSubjectRadioButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        addANewSubjectRadioButton.setText("Add a new subject");
        addANewSubjectRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                addANewSubjectRadioButtonItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel1.setText("Add Questions To Database");

        nextButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        nextButton.setText("NEXT");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        cancelButton.setText("CANCEL");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addANewSubjectRadioButton)
                    .addComponent(addToExistingSubjectRadioButton))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelButton)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(addToExistingSubjectRadioButton)
                .addGap(18, 18, 18)
                .addComponent(addANewSubjectRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addToExistingSubjectRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToExistingSubjectRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addToExistingSubjectRadioButtonActionPerformed

    private void addToExistingSubjectRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_addToExistingSubjectRadioButtonItemStateChanged
    }//GEN-LAST:event_addToExistingSubjectRadioButtonItemStateChanged

    private void addANewSubjectRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_addANewSubjectRadioButtonItemStateChanged
    }//GEN-LAST:event_addANewSubjectRadioButtonItemStateChanged

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if (addANewSubjectRadioButton.isSelected()) {
            contentPanel = new JPanel(new BorderLayout());
            adminFrame.rightPanel = new AddNewSubjectPanel(this, adminFrame);

            adminFrame.jSplitPane1 = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, true, adminFrame.leftPanel, adminFrame.rightPanel);
            adminFrame.jSplitPane1.setDividerLocation(120);

            contentPanel.add(adminFrame.jSplitPane1, BorderLayout.CENTER);
            adminFrame.setContentPane(contentPanel);
            adminFrame.getRootPane().updateUI();
            SwingUtilities.updateComponentTreeUI(this);
        } else if (addToExistingSubjectRadioButton.isSelected()) {
            contentPanel = new JPanel(new BorderLayout());
            adminFrame.rightPanel = new AddQuestionsToExistingSubjectPanel(this, adminFrame);

            adminFrame.jSplitPane1 = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, true, adminFrame.leftPanel, adminFrame.rightPanel);
            adminFrame.jSplitPane1.setDividerLocation(120);

            contentPanel.add(adminFrame.jSplitPane1, BorderLayout.CENTER);
            adminFrame.setContentPane(contentPanel);
            adminFrame.getRootPane().updateUI();
            SwingUtilities.updateComponentTreeUI(this);
        } else {
            JOptionPane.showMessageDialog(adminFrame, "Select an option!!");
        }
    }//GEN-LAST:event_nextButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addANewSubjectRadioButton;
    private javax.swing.JRadioButton addToExistingSubjectRadioButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nextButton;
    // End of variables declaration//GEN-END:variables
}
