/*s
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app;

import java.awt.BorderLayout;
import javax.swing.*;
 
/**
 *
 * @author professional
 */
public class Admin extends javax.swing.JFrame {

    private JPanel contentPanel;
    static boolean conductTest;

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        setSize(700, 730);
        conductTest = true;
        contentPanel = new JPanel(new BorderLayout());
        rightPanel = new LogoDisplayPanel();

        jSplitPane1 = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, true, leftPanel, rightPanel);
        jSplitPane1.setDividerLocation(120);
        jSplitPane1.setOneTouchExpandable(true);

        contentPanel.add(jSplitPane1, BorderLayout.CENTER);
        setContentPane(contentPanel);
        getRootPane().updateUI();
        SwingUtilities.updateComponentTreeUI(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminPanel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        conductTestButton = new javax.swing.JButton();
        AddQuestionsToDatabaseButton = new javax.swing.JButton();
        createTemplateButton = new javax.swing.JButton();
        AddUserButton = new javax.swing.JButton();
        ImportQuestionsFromFileButton = new javax.swing.JButton();
        reportButton = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        testMenu = new javax.swing.JMenu();
        conductTestMenuItem = new javax.swing.JMenuItem();
        showStatusMenuItem = new javax.swing.JMenuItem();
        templateMenu = new javax.swing.JMenu();
        createTemplateMenuItem = new javax.swing.JMenuItem();
        editTemplateMenuItem = new javax.swing.JMenuItem();
        deleteTemplateMenuItem = new javax.swing.JMenuItem();
        subjectMenu = new javax.swing.JMenu();
        importMenuItem = new javax.swing.JMenuItem();
        addMenuItem = new javax.swing.JMenuItem();
        reportsMenu = new javax.swing.JMenu();
        studentWiseMenuItem = new javax.swing.JMenuItem();
        subjectWiseMenuItem = new javax.swing.JMenuItem();
        divisionWiseMenuItem = new javax.swing.JMenuItem();
        standardWiseMenuItem = new javax.swing.JMenuItem();
        invigilatorAccountMenu = new javax.swing.JMenu();
        createAccountMenuItem = new javax.swing.JMenuItem();
        editAccountMenuItem = new javax.swing.JMenuItem();
        deleteAccountMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator");

        adminPanel.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(120);
        jSplitPane1.setEnabled(false);
        jSplitPane1.setOneTouchExpandable(true);

        conductTestButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        conductTestButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/Scheduled-icon.png"))); // NOI18N
        conductTestButton.setText("<html>Conduct<br><p align = center> Test</p></html>");
        conductTestButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        conductTestButton.setMinimumSize(new java.awt.Dimension(86, 100));
        conductTestButton.setPreferredSize(new java.awt.Dimension(86, 100));
        conductTestButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        conductTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conductTestButtonconductTestButtonActionPerformed(evt);
            }
        });

        AddQuestionsToDatabaseButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        AddQuestionsToDatabaseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/Subject.png"))); // NOI18N
        AddQuestionsToDatabaseButton.setText("<html><body align = center> Add <br> Questions </body></html>");
        AddQuestionsToDatabaseButton.setToolTipText("");
        AddQuestionsToDatabaseButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddQuestionsToDatabaseButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        AddQuestionsToDatabaseButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AddQuestionsToDatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddQuestionsToDatabaseButtonActionPerformed(evt);
            }
        });

        createTemplateButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        createTemplateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/templateIcon.png"))); // NOI18N
        createTemplateButton.setText("<html><body align = center>Create <br>Template</body></html>");
        createTemplateButton.setToolTipText("");
        createTemplateButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createTemplateButton.setMinimumSize(new java.awt.Dimension(86, 100));
        createTemplateButton.setPreferredSize(new java.awt.Dimension(86, 100));
        createTemplateButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        createTemplateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTemplateButtonjButton3ActionPerformed(evt);
            }
        });

        AddUserButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        AddUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/AccountIcon.png"))); // NOI18N
        AddUserButton.setText("<html><body align = center>Create<br> Account</html>");
        AddUserButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddUserButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        AddUserButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AddUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserButtonAddUserButtonActionPerformed(evt);
            }
        });

        ImportQuestionsFromFileButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ImportQuestionsFromFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/ImportIcon.png"))); // NOI18N
        ImportQuestionsFromFileButton.setText("<html><body align = center> Import<br> Questions</body></html>");
        ImportQuestionsFromFileButton.setToolTipText("");
        ImportQuestionsFromFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ImportQuestionsFromFileButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ImportQuestionsFromFileButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ImportQuestionsFromFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportQuestionsFromFileButtonImportQuestionsFromFileButtonActionPerformed(evt);
            }
        });

        reportButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        reportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/ReportIcon.png"))); // NOI18N
        reportButton.setText("<html><body>Student<br><p align = \"center\">Report</p></body></html>");
        reportButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reportButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        reportButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonreportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
            .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(leftPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ImportQuestionsFromFileButton)
                        .addComponent(createTemplateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(conductTestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddQuestionsToDatabaseButton)
                        .addComponent(AddUserButton)
                        .addComponent(reportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
            .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(leftPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(conductTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(createTemplateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(ImportQuestionsFromFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(AddQuestionsToDatabaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(AddUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(reportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(57, Short.MAX_VALUE)))
        );

        jSplitPane1.setLeftComponent(leftPanel);

        rightPanel.setMaximumSize(new java.awt.Dimension(578, 564));
        rightPanel.setPreferredSize(new java.awt.Dimension(578, 564));

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(rightPanel);

        adminPanel.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setAlignmentX(2.0F);

        testMenu.setMnemonic('T');
        testMenu.setText("   Test   ");
        testMenu.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        testMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testMenuActionPerformed(evt);
            }
        });

        conductTestMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        conductTestMenuItem.setMnemonic('C');
        conductTestMenuItem.setText("Conduct Test");
        conductTestMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conductTestMenuItemActionPerformed(evt);
            }
        });
        testMenu.add(conductTestMenuItem);

        showStatusMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        showStatusMenuItem.setMnemonic('V');
        showStatusMenuItem.setText("View Status");
        showStatusMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStatusMenuItemActionPerformed(evt);
            }
        });
        testMenu.add(showStatusMenuItem);

        jMenuBar1.add(testMenu);

        templateMenu.setMnemonic('p');
        templateMenu.setText("   Template   ");
        templateMenu.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N

        createTemplateMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        createTemplateMenuItem.setMnemonic('r');
        createTemplateMenuItem.setText("Create");
        createTemplateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTemplateMenuItemActionPerformed(evt);
            }
        });
        templateMenu.add(createTemplateMenuItem);

        editTemplateMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        editTemplateMenuItem.setMnemonic('e');
        editTemplateMenuItem.setText("Edit");
        editTemplateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTemplateMenuItemActionPerformed(evt);
            }
        });
        templateMenu.add(editTemplateMenuItem);

        deleteTemplateMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        deleteTemplateMenuItem.setMnemonic('d');
        deleteTemplateMenuItem.setText("Delete");
        deleteTemplateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTemplateMenuItemActionPerformed(evt);
            }
        });
        templateMenu.add(deleteTemplateMenuItem);

        jMenuBar1.add(templateMenu);

        subjectMenu.setMnemonic('S');
        subjectMenu.setText("   Subject   ");
        subjectMenu.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N

        importMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        importMenuItem.setMnemonic('I');
        importMenuItem.setText("Import from file");
        importMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importMenuItemActionPerformed(evt);
            }
        });
        subjectMenu.add(importMenuItem);

        addMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        addMenuItem.setMnemonic('a');
        addMenuItem.setText("Add to database");
        addMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMenuItemActionPerformed(evt);
            }
        });
        subjectMenu.add(addMenuItem);

        jMenuBar1.add(subjectMenu);

        reportsMenu.setMnemonic('r');
        reportsMenu.setText("   Reports   ");
        reportsMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        reportsMenu.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N

        studentWiseMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK));
        studentWiseMenuItem.setText("Student Wise");
        studentWiseMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentWiseMenuItemActionPerformed(evt);
            }
        });
        reportsMenu.add(studentWiseMenuItem);

        subjectWiseMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK));
        subjectWiseMenuItem.setText("Subject Wise");
        subjectWiseMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectWiseMenuItemActionPerformed(evt);
            }
        });
        reportsMenu.add(subjectWiseMenuItem);

        divisionWiseMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        divisionWiseMenuItem.setText("Division Wise");
        divisionWiseMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionWiseMenuItemActionPerformed(evt);
            }
        });
        reportsMenu.add(divisionWiseMenuItem);

        standardWiseMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK));
        standardWiseMenuItem.setText("Standard Wise");
        standardWiseMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardWiseMenuItemActionPerformed(evt);
            }
        });
        reportsMenu.add(standardWiseMenuItem);

        jMenuBar1.add(reportsMenu);

        invigilatorAccountMenu.setMnemonic('I');
        invigilatorAccountMenu.setText("   Invigilator Account   ");
        invigilatorAccountMenu.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N

        createAccountMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        createAccountMenuItem.setMnemonic('r');
        createAccountMenuItem.setText("Create");
        createAccountMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountMenuItemActionPerformed(evt);
            }
        });
        invigilatorAccountMenu.add(createAccountMenuItem);

        editAccountMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        editAccountMenuItem.setMnemonic('e');
        editAccountMenuItem.setText("Edit");
        editAccountMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAccountMenuItemActionPerformed(evt);
            }
        });
        invigilatorAccountMenu.add(editAccountMenuItem);

        deleteAccountMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        deleteAccountMenuItem.setMnemonic('d');
        deleteAccountMenuItem.setText("Delete");
        deleteAccountMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountMenuItemActionPerformed(evt);
            }
        });
        invigilatorAccountMenu.add(deleteAccountMenuItem);

        jMenuBar1.add(invigilatorAccountMenu);

        helpMenu.setMnemonic('H');
        helpMenu.setText("   Help   ");
        helpMenu.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem3.setMnemonic('T');
        jMenuItem3.setText("Take A Tour");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        helpMenu.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem4.setMnemonic('A');
        jMenuItem4.setText("About");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        helpMenu.add(jMenuItem4);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createTemplateMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTemplateMenuItemActionPerformed
        contentPanel = new JPanel(new BorderLayout());
        rightPanel = new CreateTemplatePanel(this);

        jSplitPane1 = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, true, leftPanel, rightPanel);
        jSplitPane1.setDividerLocation(120);
        jSplitPane1.setOneTouchExpandable(true);

        contentPanel.add(jSplitPane1, BorderLayout.CENTER);
        setContentPane(contentPanel);
        getRootPane().updateUI();
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_createTemplateMenuItemActionPerformed

    private void importMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importMenuItemActionPerformed
        ImportFromExcel importFromExcel = new ImportFromExcel(this);
    }//GEN-LAST:event_importMenuItemActionPerformed

    private void addMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMenuItemActionPerformed
        contentPanel = new JPanel(new BorderLayout());
        rightPanel = new AddQuestionToDatabase(this);

        jSplitPane1 = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, true, leftPanel, rightPanel);
        jSplitPane1.setDividerLocation(120);

        contentPanel.add(jSplitPane1, BorderLayout.CENTER);
        setContentPane(contentPanel);
        getRootPane().updateUI();
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_addMenuItemActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TourFrame tourFrame = new TourFrame();
        tourFrame.setVisible(true);
//        Admin admin = new Admin();
//        admin.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void conductTestButtonconductTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conductTestButtonconductTestButtonActionPerformed
        conductTestMenuItemActionPerformed(evt);
    }//GEN-LAST:event_conductTestButtonconductTestButtonActionPerformed

    private void createTemplateButtonjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTemplateButtonjButton3ActionPerformed
        createTemplateMenuItemActionPerformed(evt);
    }//GEN-LAST:event_createTemplateButtonjButton3ActionPerformed

    private void AddUserButtonAddUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserButtonAddUserButtonActionPerformed
        createAccountMenuItemActionPerformed(evt);
    }//GEN-LAST:event_AddUserButtonAddUserButtonActionPerformed

    private void ImportQuestionsFromFileButtonImportQuestionsFromFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportQuestionsFromFileButtonImportQuestionsFromFileButtonActionPerformed
        importMenuItemActionPerformed(evt);
    }//GEN-LAST:event_ImportQuestionsFromFileButtonImportQuestionsFromFileButtonActionPerformed

    private void reportButtonreportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonreportButtonActionPerformed
        studentWiseMenuItemActionPerformed(evt);
    }//GEN-LAST:event_reportButtonreportButtonActionPerformed

    private void conductTestMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conductTestMenuItemActionPerformed
        if (conductTest) {
            contentPanel = new JPanel(new BorderLayout());
            rightPanel = new ConductTestPanel(this);

            jSplitPane1 = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, true, leftPanel, rightPanel);
            jSplitPane1.setDividerLocation(120);
            jSplitPane1.setOneTouchExpandable(true);

            contentPanel.add(jSplitPane1, BorderLayout.CENTER);
            setContentPane(contentPanel);
            getRootPane().updateUI();
            SwingUtilities.updateComponentTreeUI(this);
        } else {
            JOptionPane.showMessageDialog(this, "Test Already Scheduled. You cannot schedule another");
        }
    }//GEN-LAST:event_conductTestMenuItemActionPerformed

    private void testMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testMenuActionPerformed

    private void createAccountMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountMenuItemActionPerformed
        contentPanel = new JPanel(new BorderLayout());
        rightPanel = new InvigilatorCreateAccount(this);

        jSplitPane1 = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, true, leftPanel, rightPanel);
        jSplitPane1.setDividerLocation(120);
        jSplitPane1.setOneTouchExpandable(true);

        contentPanel.add(jSplitPane1, BorderLayout.CENTER);
        setContentPane(contentPanel);
        getRootPane().updateUI();
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_createAccountMenuItemActionPerformed

    private void editAccountMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAccountMenuItemActionPerformed
        contentPanel = new JPanel(new BorderLayout());
        rightPanel = new InvigilatorEditAccount(this);

        jSplitPane1 = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, true, leftPanel, rightPanel);
        jSplitPane1.setDividerLocation(120);
        jSplitPane1.setOneTouchExpandable(true);

        contentPanel.add(jSplitPane1, BorderLayout.CENTER);
        setContentPane(contentPanel);
        getRootPane().updateUI();
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_editAccountMenuItemActionPerformed

    private void deleteAccountMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountMenuItemActionPerformed
        contentPanel = new JPanel(new BorderLayout());
        rightPanel = new InvigilatorDeleteAccount(this);

        jSplitPane1 = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, true, leftPanel, rightPanel);
        jSplitPane1.setDividerLocation(120);
        jSplitPane1.setOneTouchExpandable(true);

        contentPanel.add(jSplitPane1, BorderLayout.CENTER);
        setContentPane(contentPanel);
        getRootPane().updateUI();
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_deleteAccountMenuItemActionPerformed

    private void showStatusMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStatusMenuItemActionPerformed
        contentPanel = new JPanel(new BorderLayout());
        rightPanel = new TestStatusPanel(this);

        jSplitPane1 = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, true, leftPanel, rightPanel);
        jSplitPane1.setDividerLocation(120);
        jSplitPane1.setOneTouchExpandable(true);

        contentPanel.add(jSplitPane1, BorderLayout.CENTER);
        setContentPane(contentPanel);
        getRootPane().updateUI();
        SwingUtilities.updateComponentTreeUI(this);

    }//GEN-LAST:event_showStatusMenuItemActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        contentPanel = new JPanel(new BorderLayout());
        rightPanel = new AboutPanel(this);

        jSplitPane1 = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, true, leftPanel, rightPanel);
        jSplitPane1.setDividerLocation(120);
        jSplitPane1.setOneTouchExpandable(true);

        contentPanel.add(jSplitPane1, BorderLayout.CENTER);
        setContentPane(contentPanel);
        getRootPane().updateUI();
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void AddQuestionsToDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddQuestionsToDatabaseButtonActionPerformed
        addMenuItemActionPerformed(evt);
    }//GEN-LAST:event_AddQuestionsToDatabaseButtonActionPerformed

    private void studentWiseMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentWiseMenuItemActionPerformed
        contentPanel = new JPanel(new BorderLayout());
        rightPanel = new StudentWiseReportPanel(this);

        jSplitPane1 = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, true, leftPanel, rightPanel);
        jSplitPane1.setDividerLocation(120);

        contentPanel.add(jSplitPane1, BorderLayout.CENTER);
        setContentPane(contentPanel);
        getRootPane().updateUI();
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_studentWiseMenuItemActionPerformed

    private void subjectWiseMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectWiseMenuItemActionPerformed
        contentPanel = new JPanel(new BorderLayout());
        rightPanel = new SubjectWiseReportPanel(this);

        jSplitPane1 = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, true, leftPanel, rightPanel);
        jSplitPane1.setDividerLocation(120);

        contentPanel.add(jSplitPane1, BorderLayout.CENTER);
        setContentPane(contentPanel);
        getRootPane().updateUI();
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_subjectWiseMenuItemActionPerformed

    private void divisionWiseMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionWiseMenuItemActionPerformed
        contentPanel = new JPanel(new BorderLayout());
        rightPanel = new DivisionWiseReportPanel(this);

        jSplitPane1 = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, true, leftPanel, rightPanel);
        jSplitPane1.setDividerLocation(120);

        contentPanel.add(jSplitPane1, BorderLayout.CENTER);
        setContentPane(contentPanel);
        getRootPane().updateUI();
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_divisionWiseMenuItemActionPerformed

    private void standardWiseMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardWiseMenuItemActionPerformed
        contentPanel = new JPanel(new BorderLayout());
        rightPanel = new StandardWiseReportPanel(this);

        jSplitPane1 = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, true, leftPanel, rightPanel);
        jSplitPane1.setDividerLocation(120);

        contentPanel.add(jSplitPane1, BorderLayout.CENTER);
        setContentPane(contentPanel);
        getRootPane().updateUI();
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_standardWiseMenuItemActionPerformed

    private void editTemplateMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTemplateMenuItemActionPerformed
        contentPanel = new JPanel(new BorderLayout());
        rightPanel = new EditTemplateNamePanel(this);

        jSplitPane1 = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, true, leftPanel, rightPanel);
        jSplitPane1.setDividerLocation(120);

        contentPanel.add(jSplitPane1, BorderLayout.CENTER);
        setContentPane(contentPanel);
        getRootPane().updateUI();
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_editTemplateMenuItemActionPerformed

    private void deleteTemplateMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTemplateMenuItemActionPerformed
        contentPanel = new JPanel(new BorderLayout());
        rightPanel = new DeleteTemplateNamePanel(this);

        jSplitPane1 = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, true, leftPanel, rightPanel);
        jSplitPane1.setDividerLocation(120);

        contentPanel.add(jSplitPane1, BorderLayout.CENTER);
        setContentPane(contentPanel);
        getRootPane().updateUI();
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_deleteTemplateMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
            UIManager.setLookAndFeel("com.plaf.hifi.HiFiLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Admin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddQuestionsToDatabaseButton;
    private javax.swing.JButton AddUserButton;
    private javax.swing.JButton ImportQuestionsFromFileButton;
    private javax.swing.JMenuItem addMenuItem;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JButton conductTestButton;
    private javax.swing.JMenuItem conductTestMenuItem;
    private javax.swing.JMenuItem createAccountMenuItem;
    private javax.swing.JButton createTemplateButton;
    private javax.swing.JMenuItem createTemplateMenuItem;
    private javax.swing.JMenuItem deleteAccountMenuItem;
    private javax.swing.JMenuItem deleteTemplateMenuItem;
    private javax.swing.JMenuItem divisionWiseMenuItem;
    private javax.swing.JMenuItem editAccountMenuItem;
    private javax.swing.JMenuItem editTemplateMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem importMenuItem;
    private javax.swing.JMenu invigilatorAccountMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    protected javax.swing.JSplitPane jSplitPane1;
    protected javax.swing.JPanel leftPanel;
    private javax.swing.JButton reportButton;
    private javax.swing.JMenu reportsMenu;
    protected javax.swing.JPanel rightPanel;
    private javax.swing.JMenuItem showStatusMenuItem;
    private javax.swing.JMenuItem standardWiseMenuItem;
    private javax.swing.JMenuItem studentWiseMenuItem;
    private javax.swing.JMenu subjectMenu;
    private javax.swing.JMenuItem subjectWiseMenuItem;
    private javax.swing.JMenu templateMenu;
    private javax.swing.JMenu testMenu;
    // End of variables declaration//GEN-END:variables
}
