/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Jaggu Movies
 */
public class InvigilatorEditAccount extends javax.swing.JPanel {
    boolean flag;
    Connection con;
    Statement s;
    Admin adminFrame;
    /**
     * Creates new form InvigilatorEditAccount
     */
    public InvigilatorEditAccount(Admin adminFrame) {
        this.adminFrame = adminFrame;
        initComponents();
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        
        try {
            con = DriverManager.getConnection("jdbc:odbc:ProjectDatabase", "", "");
            s = con.createStatement();
            s.execute("select userName from Invigilator"); // insert some data into the table  
            ResultSet rs = s.getResultSet();
            while(rs.next())
            {
                usernameComboBox.addItem(rs.getString("userName"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changePasswordButton = new javax.swing.JButton();
        newPasswordLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameComboBox = new javax.swing.JComboBox();
        changePasswordField = new javax.swing.JPasswordField();
        cancelButton = new javax.swing.JButton();

        changePasswordButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        changePasswordButton.setText("Change");
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });

        newPasswordLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        newPasswordLabel.setText("New Password");

        usernameLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        usernameLabel.setText("username");

        usernameComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                usernameComboBoxItemStateChanged(evt);
            }
        });
        usernameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameComboBoxActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameLabel)
                    .addComponent(newPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(changePasswordField)
                    .addComponent(usernameComboBox, 0, 92, Short.MAX_VALUE))
                .addGap(91, 91, 91))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameLabel)
                    .addComponent(usernameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newPasswordLabel)
                    .addComponent(changePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        flag = true;
        String temp = new String( changePasswordField.getPassword());
        if (temp.equals(""))
        {
            JOptionPane.showMessageDialog(adminFrame,"Enter Password");
            flag = false;
        }
        try {
            String userName = (String) usernameComboBox.getSelectedItem();
            String changePassword = new String(changePasswordField.getPassword());
            if(flag)
            {
                s.execute("update Invigilator set password ='" + changePassword + "'where userName ='" + userName + "'"); // insert some data into the table
                JOptionPane.showMessageDialog(adminFrame,"Password changed");
            }
            s.close();
            con.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_changePasswordButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void usernameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameComboBoxActionPerformed

    private void usernameComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_usernameComboBoxItemStateChanged
        changePasswordField.setText("");
    }//GEN-LAST:event_usernameComboBoxItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JPasswordField changePasswordField;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JComboBox usernameComboBox;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
