/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class ShowResultPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShowAnalysisPanel
     */
    ClientTestScreen clientTestScreen;
    ShowAnalysisThread showAnalysisThread;

    public ShowResultPanel(ClientTestScreen client) {
        initComponents();
        this.clientTestScreen = client;
        this.marksScoredLabel.setText(Integer.toString(client.totalMarksScored));
        this.totalMarksLabel.setText(Integer.toString(client.records.length));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        showAnalysisButton = new javax.swing.JButton();
        totalMarkstHeaderLabel = new javax.swing.JLabel();
        totalMarksLabel = new javax.swing.JLabel();
        marksScoredHeaderLabel = new javax.swing.JLabel();
        marksScoredLabel = new javax.swing.JLabel();

        exitButton.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        exitButton.setText("EXIT");
        exitButton.setToolTipText("");
        exitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        showAnalysisButton.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        showAnalysisButton.setText("<html><body align=center>  SHOW<br> ANALYSIS</body></html>");
        showAnalysisButton.setToolTipText("");
        showAnalysisButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        showAnalysisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAnalysisButtonActionPerformed(evt);
            }
        });

        totalMarkstHeaderLabel.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        totalMarkstHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalMarkstHeaderLabel.setText("TOTAL MARKS :");

        totalMarksLabel.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        totalMarksLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        marksScoredHeaderLabel.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        marksScoredHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marksScoredHeaderLabel.setText("MARKS SCORED :");

        marksScoredLabel.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        marksScoredLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalMarkstHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marksScoredHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(marksScoredLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(totalMarksLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(showAnalysisButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(marksScoredLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marksScoredHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalMarkstHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalMarksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showAnalysisButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(190, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showAnalysisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAnalysisButtonActionPerformed
        try {
            clientTestScreen.startClientCommunication.outObj.writeBoolean(true);
            clientTestScreen.startClientCommunication.outObj.flush();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        try {
            clientTestScreen.analysis = clientTestScreen.startClientCommunication.inObj.readBoolean();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        if (clientTestScreen.analysis) {
            clientTestScreen.questionsSplitPane.setLeftComponent(clientTestScreen.questionNavigationScrollPane);

            clientTestScreen.questionsSplitPane.setRightComponent(clientTestScreen.questionPanel);

            clientTestScreen.questionsSplitPane.setDividerLocation(100);
            clientTestScreen.startTestOrAnalysis();
        }
        else {
            JOptionPane.showMessageDialog(clientTestScreen, "Cannot display analysis now...Test of other students is being conducted");
        }
    }//GEN-LAST:event_showAnalysisButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel marksScoredHeaderLabel;
    private javax.swing.JLabel marksScoredLabel;
    private javax.swing.JButton showAnalysisButton;
    private javax.swing.JLabel totalMarksLabel;
    private javax.swing.JLabel totalMarkstHeaderLabel;
    // End of variables declaration//GEN-END:variables
}
