/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app;

import java.awt.BorderLayout;
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author abd
 */
public class StudentWiseReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentWiseReportPanel
     */
    Admin adminFrame;
    private JPanel contentPanel;
    Connection con;
    Statement s;
    ResultSet rs;
    String nameOfStudent;
    Integer roll;
    int standard;
    String division;
    int batch;
    boolean flag;

    public StudentWiseReportPanel(Admin adminFrame) {
        initComponents();
        this.adminFrame = adminFrame;
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        try {
            con = DriverManager.getConnection("jdbc:odbc:ProjectDatabase");
            s = con.createStatement();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        standardComboBox.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        standardOfStudentLabel = new javax.swing.JLabel();
        standardComboBox = new javax.swing.JComboBox();
        divisionLabel1 = new javax.swing.JLabel();
        divisionLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        rollNumberLabel = new javax.swing.JLabel();
        showButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        divisionList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        batchList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        nameList = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        rollNumberList = new javax.swing.JList();

        standardOfStudentLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        standardOfStudentLabel.setText("Standard");

        standardComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "IX", "X" }));
        standardComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                standardComboBoxItemStateChanged(evt);
            }
        });
        standardComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardComboBoxActionPerformed(evt);
            }
        });

        divisionLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        divisionLabel1.setText("Division");

        divisionLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        divisionLabel.setText("Batch");

        nameLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        nameLabel.setText("Name");

        rollNumberLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        rollNumberLabel.setText("Roll Number");

        showButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showButton.setText("Show");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        divisionList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                divisionListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(divisionList);

        batchList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                batchListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(batchList);

        nameList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                nameListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(nameList);

        rollNumberList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                rollNumberListValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(rollNumberList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(standardOfStudentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rollNumberLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(divisionLabel1)
                    .addComponent(divisionLabel)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(standardComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addComponent(showButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(standardOfStudentLabel)
                            .addComponent(standardComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(divisionLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(divisionLabel))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(nameLabel)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rollNumberLabel))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(showButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void standardComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_standardComboBoxItemStateChanged
    }//GEN-LAST:event_standardComboBoxItemStateChanged

    private void standardComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardComboBoxActionPerformed
        try {
            String temp = standardComboBox.getSelectedItem().toString();
            standard = temp.equals("IX") ? 9 : 10;
            s.execute("select distinct division from Student where standard = " + standard);
            rs = s.getResultSet();
            if (rs != null) {
                Vector<String> div = new Vector<>();
                while (rs.next()) {
                    String st = rs.getString(1);
                    div.add(st);
                }
                divisionList.setListData(div);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        divisionList.validate();
        divisionList.updateUI();
        try {
            s.execute("select distinct batch from Student ");
            rs = s.getResultSet();
            if (rs != null) {
                Vector<String> batchVec = new Vector<>();
                while (rs.next()) {
                    String st = rs.getString(1);
                    batchVec.add(st);
                }
                batchList.setListData(batchVec);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        batchList.validate();
        batchList.updateUI();
    }//GEN-LAST:event_standardComboBoxActionPerformed

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        flag = false;
        
        checkDivision();
        if (!flag) {
            return;
        }

        checkBatch();
        if (!flag) {
            return;
        }

        checkName();
        if (!flag) {
            return;
        }

        if (flag) {
            roll = new Integer(rollNumberList.getSelectedValue().toString());
            nameOfStudent = (nameList.getSelectedValue().toString());
            contentPanel = new JPanel(new BorderLayout());
            adminFrame.rightPanel = new ShowStudentReportPanel(adminFrame, this);

            adminFrame.jSplitPane1 = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, true, adminFrame.leftPanel, adminFrame.rightPanel);
            adminFrame.jSplitPane1.setDividerLocation(120);

            contentPanel.add(adminFrame.jSplitPane1, BorderLayout.CENTER);
            adminFrame.setContentPane(contentPanel);
            adminFrame.getRootPane().updateUI();
            SwingUtilities.updateComponentTreeUI(this);
        }
    }//GEN-LAST:event_showButtonActionPerformed

    private void divisionListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_divisionListValueChanged

        rollNumberList.setListData(new Vector());
        nameList.setListData(new Vector());
    }//GEN-LAST:event_divisionListValueChanged

    private void batchListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_batchListValueChanged

        try {
            division = divisionList.getSelectedValue().toString();
            batch = Integer.parseInt(batchList.getSelectedValue().toString());
            s.execute("select firstName , lastName from Student where standard = " + standard + "and division = '" + division + "' and batch = " + batch);
            rs = s.getResultSet();
            if (rs != null) {
                Vector<String> name = new Vector<>();
                while (rs.next()) {
                    String tempName = rs.getString("firstName") + " " + rs.getString("lastName");

                    name.add(tempName);
                }
                nameList.setListData(name);
            }

            s.execute("select rollNumber from Student where standard = " + standard + "and division = '" + division + "'and batch = " + batch);
            rs = s.getResultSet();
            if (rs != null) {
                Vector<String> roll = new Vector<>();
                while (rs.next()) {
                    String st = rs.getString(1);
                    roll.add(st);
                }
                rollNumberList.setListData(roll);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        nameList.validate();
        nameList.updateUI();
        rollNumberList.validate();
        rollNumberList.updateUI();
    }//GEN-LAST:event_batchListValueChanged

    private void nameListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_nameListValueChanged
        rollNumberList.setSelectedIndex(nameList.getSelectedIndex());
    }//GEN-LAST:event_nameListValueChanged

    private void rollNumberListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_rollNumberListValueChanged
        nameList.setSelectedIndex(rollNumberList.getSelectedIndex());
    }//GEN-LAST:event_rollNumberListValueChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList batchList;
    private javax.swing.JLabel divisionLabel;
    private javax.swing.JLabel divisionLabel1;
    private javax.swing.JList divisionList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JList nameList;
    private javax.swing.JLabel rollNumberLabel;
    private javax.swing.JList rollNumberList;
    private javax.swing.JButton showButton;
    private javax.swing.JComboBox standardComboBox;
    private javax.swing.JLabel standardOfStudentLabel;
    // End of variables declaration//GEN-END:variables

    private void checkDivision() {
        if (divisionList.getSelectedValue() == null) {
            flag = false;
            JOptionPane.showMessageDialog(contentPanel, "Select a  division !!");
            return;
        }
        flag = true;
    }

    private void checkBatch() {
        if (batchList.getSelectedValue() == null) {
            flag = false;
            JOptionPane.showMessageDialog(contentPanel, "Select a batch !!");
            return;
        }
        flag = true;
    }

    private void checkName() {
        if (nameList.getSelectedValue() == null) {
            flag = false;
            JOptionPane.showMessageDialog(contentPanel, "Select a  student !!");
            return;
        }
        flag = true;
    }
}